name: Weekly PR Review Report

on:
  # Scheduled automatic run
  schedule:
    - cron: "0 9 * * MON"

  # Manual trigger with inputs
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository name to generate report (default: NethermindEth/nethermind)"
        required: false
        default: "NethermindEth/nethermind"
      days:
        description: "Number of days to look back for reviews"
        required: false
        default: "7"

permissions:
  contents: read
  pull-requests: read

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Generate and send PR review report
        run: |        
          REPO="${{ github.event.inputs.repo || 'NethermindEth/nethermind' }}"
          DAYS="${{ github.event.inputs.days || 7 }}"
          echo "Generating report for repo '$REPO' for the last $DAYS days..."
          python generate_pr_report.py "$REPO" "$DAYS"
